baseURL = "https://example.org/"
languageCode = "en-us"
title = "Hugo site with Classless theme"

# Remove files from destination not found in static directories
cleandestinationdir = true
enableEmoji = true
disableFastRender = true
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = "emacs"

[Params]
  mainSections = ["posts"]

  # css = [] # default = ["bmfw.css", "ox-hugo.css"]
