baseURL = "https://example.org/"
languageCode = "en-us"
title = "Hugo MWE"

# Remove files from destination not found in static directories
cleandestinationdir = true
enableEmoji = true
disableFastRender = true
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  subTitle = "Minimum working examples for testing out Hugo issues and features"
  mainSections = ["posts"]

  [Params.source]
    url = "https://gitlab.com/hugo-mwe/hugo-mwe" # Mandatory
